import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const fixPunycodeImportPlugin = {
  name: 'fix-punycode-import',
  setup(build) {
    build.onResolve({ filter: /^punycode\/$/ }, args => {
      return {
        path: 'punycode',
        external: true, // or true, depending on your bundling strategy
      };
    });
  },
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2020",
	platform: "node",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	mainFields: ['module', 'main'],
	plugins: [fixPunycodeImportPlugin]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
